// File generated by FlutterFire CLI - Modified to use environment variables
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Firebase credentials are read from environment variables defined at build time.
/// Set them using --dart-define flags:
/// ```bash
/// flutter run \
///   --dart-define=FIREBASE_WEB_API_KEY=your_key \
///   --dart-define=FIREBASE_ANDROID_API_KEY=your_key
/// ```
class DefaultFirebaseOptions {
  // Read API keys from environment (passed via --dart-define)
  static const String _webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: '');
  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: '');

  // Firestore project constants (shared across platforms)
  static const String _projectId = 'fyp-helper';
  static const String _messagingSenderId = '389478276701';
  static const String _authDomain = 'fyp-helper.firebaseapp.com';
  static const String _databaseUrl =
      'https://fyp-helper-default-rtdb.asia-southeast1.firebasedatabase.app';
  static const String _storageBucket = 'fyp-helper.firebasestorage.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    _validateApiKey(_webApiKey, 'Web');
    return FirebaseOptions(
      apiKey: _webApiKey,
      appId: '1:389478276701:web:a4f7fb67882d9198e777b4',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      authDomain: _authDomain,
      databaseURL: _databaseUrl,
      storageBucket: _storageBucket,
    );
  }

  static FirebaseOptions get android {
    _validateApiKey(_androidApiKey, 'Android');
    return FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:389478276701:android:72269fb6a715e97fe777b4',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      databaseURL: _databaseUrl,
      storageBucket: _storageBucket,
    );
  }

  static void _validateApiKey(String apiKey, String platform) {
    if (apiKey.isEmpty) {
      throw StateError(
        'Firebase $platform API key is missing. '
        'Pass it via: --dart-define=FIREBASE_${platform.toUpperCase()}_API_KEY=your_key',
      );
    }
  }
}