// File generated by FlutterFire CLI - Modified to use environment variables
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Firebase credentials are read from environment variables defined at build time.
/// Set them using --dart-define flags (see `run_app.ps1` and `.env.example`).
class DefaultFirebaseOptions {
  static const String _windowsApiKey =
      String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: '');
  static const String _windowsAppId =
      String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: '');
  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: '');
  static const String _webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: '');
  static const String _webAppId =
      String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: '');

  static const String _projectId = 'fyp-helper';
  static const String _messagingSenderId = '389478276701';
  static const String _authDomain = 'fyp-helper.firebaseapp.com';
  static const String _databaseUrl =
      'https://fyp-helper-default-rtdb.asia-southeast1.firebasedatabase.app';
  static const String _storageBucket = 'fyp-helper.firebasestorage.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'FYP Helper supports Android, Windows desktop, and Web (Chrome/Edge).',
        );
    }
  }

  static FirebaseOptions get web {
    final apiKey = _webApiKey.isNotEmpty ? _webApiKey : _windowsApiKey;
    final appId = _webAppId.isNotEmpty ? _webAppId : _windowsAppId;
    _validateApiKey(apiKey, 'Web');
    _validateAppId(appId, 'Web');
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      authDomain: _authDomain,
      databaseURL: _databaseUrl,
      storageBucket: _storageBucket,
    );
  }

  static FirebaseOptions get windows {
    _validateApiKey(_windowsApiKey, 'Windows');
    _validateAppId(_windowsAppId, 'Windows');
    return FirebaseOptions(
      apiKey: _windowsApiKey,
      appId: _windowsAppId,
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      authDomain: _authDomain,
      databaseURL: _databaseUrl,
      storageBucket: _storageBucket,
    );
  }

  static FirebaseOptions get android {
    _validateApiKey(_androidApiKey, 'Android');
    return FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:389478276701:android:72269fb6a715e97fe777b4',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      databaseURL: _databaseUrl,
      storageBucket: _storageBucket,
    );
  }

  static void _validateApiKey(String apiKey, String platform) {
    if (apiKey.isEmpty) {
      throw StateError(
        'Firebase $platform API key is missing. '
        'Pass it via --dart-define=FIREBASE_${platform.toUpperCase()}_API_KEY=your_key '
        '(or use .\\run_app.ps1 -chrome).',
      );
    }
  }

  static void _validateAppId(String appId, String platform) {
    if (appId.isEmpty) {
      throw StateError(
        'Firebase $platform app ID is missing. '
        'Pass it via --dart-define=FIREBASE_${platform.toUpperCase()}_APP_ID=your_app_id '
        '(or use .\\run_app.ps1 -chrome).',
      );
    }
  }
}
